name: ${project.name}
version: ${project.version}
author: SystemUpdate, cs8425
main: ${project.groupId}.${project.name}
api-version: 1.13
commands:
  basichomes: {}
  sethome:
    description: "set current location to a new home point"
    permission: basichomes.sethome
    usage: "/sethome <homeName>"
  delhome:
    description: "delete player's home point"
    permission: basichomes.delhome
    usage: "/delhome <homeName>"
  home:
    description: "teleport to player's home point"
    permission: basichomes.home
    usage: "/home <homeName>"
  homes:
    description: "list player's home point"
    permission: basichomes.homes
    usage: "/homes [playerName]"
  tpa:
    description: "ask a player to teleport to him/her"
    permission: basichomes.tpa
    usage: "/tpa <playerName>"
  tpahere:
    description: "ask a player to teleport to here"
    permission: basichomes.tpahere
    usage: "/tpahere <playerName>"
  tpaccept:
    description: "accept teleport request"
    permission: basichomes.tpaccept
    usage: "/tpaccept"
  tpdeny:
    description: "deny teleport request"
    permission: basichomes.tpdeny
    usage: "/tpdeny"
  back:
    description: "teleport back to place of death"
    permission: basichomes.tpahere
    usage: "/back"
permissions:
  basichomes.*:
    description: Gives access to all ${project.name} commands
    children:
      basichomes.sethome: true
      basichomes.delhome: true
      basichomes.home: true
      basichomes.homes: true
      basichomes.home.other: true
  basichomes.homebasic:
    description: Gives access to basic ${project.name} home commands
    children:
      basichomes.sethome: true
      basichomes.delhome: true
      basichomes.home: true
      basichomes.homes: true
      basichomes.max.5: true
  basichomes.tpbasic:
    description: Gives access to basic ${project.name} teleport commands
    children:
      basichomes.tpa: true
      basichomes.tpahere: true
      basichomes.tpaccept: true
      basichomes.tpdeny: true
  basichomes.sethome:
    description: Gives access to the /sethome command
    default: op
  basichomes.delhome:
    description: Gives access to the /delhome command
    default: op
  basichomes.home:
    description: Gives access to the /home command
    default: op
  basichomes.homes:
    description: Gives access to the /homes command
    default: op
  basichomes.max.unlimited:
    description: limit max home point count
    default: op
  basichomes.home.other:
    description: list/edit other's home point count
    default: op
  basichomes.tpa:
    description: Gives access to the /tpa command
    default: false
  basichomes.tpahere:
    description: Gives access to the /tpahere command
    default: false
  basichomes.tpaccept:
    description: Gives access to the /tpaccept command
    default: false
  basichomes.tpdeny:
    description: Gives access to the /tpdeny command
    default: false
  basichomes.back:
    description: Gives access to the /back command
    default: op
  basichomes.tpworld:
    description: Gives access to the /tpworld command
    default: op

